plugins { id 'com.android.application' }

android {
    namespace 'com.pierre.catdoorcamera'
    compileSdk 35
    buildToolsVersion "35.0.0"
    defaultConfig {
        applicationId 'com.pierre.catdoorcamera'
        minSdk 22
        targetSdk 35
        versionCode 4
        versionName '1.3'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
